#DB Configuration
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/microservice
    username: root
    password: password
  redis:
    host: 192.168.2.100
    port: 6379

#Logging
logging:
  level:
    ccc.springboot.coconut: debug


